image: Visual Studio 2017

environment:
  NUGET_API_KEY:
    secure: 8doivbDJ+FYDneG9TYTCJS2JLzqK7JrzY67sft6NYzMKJMSKg4S4IrK4WuWFPcf0

pull_requests:
  do_not_increment_build_number: true

build_script:
- ps: |
    & .\build.cmd AppVeyor NuGetPublicKey="$($Env:NUGET_API_KEY)" BuildVersion=git BuildNumber=$($Env:APPVEYOR_BUILD_NUMBER)

test: off

artifacts:
- path: build\NuGetPackages\*.nupkg
  name: NuGet

deploy: off

