image: Visual Studio 2017

environment:
  NUGET_API_KEY:
    secure: S8yqXioi59Oq5FHSf89z4nARfAOqAUNr3a0atR/DiHXATULZ+Ui5yttBXQzGg0Tv

pull_requests:
  do_not_increment_build_number: true

build_script:
- ps: |
    & .\build.cmd AppVeyor NuGetPublicKey="$($Env:NUGET_API_KEY)" BuildVersion=git BuildNumber=$($Env:APPVEYOR_BUILD_NUMBER)

test: off

artifacts:
- path: build\NuGetPackages\*.nupkg
  name: NuGet

deploy: off

